### ISSUE TITLE
Error LastFm User: User not found

### ISSUE THREAD

**Issue by parryg** [dharma-guardian/iTunesPlayCountFromLastFM#5]
Receiving this error on the .App ( v0.1.1) version of this, I know it's correct though (parryg), any help would be appreciated.

**Comment by eppfel** [comment]
I cannot reproduce the error on my side. Even when I use your username, everything works like expected. Can you specify a little more context, like OS Version, iTunes Version, the exact steps in order to reproduce it.
Did not use the script for some time. Was actually surprised, that it works smoothly on my side. 😄

**Comment by parryg** [comment]
Thanks for the quick reply.  I've just gone to record my screen to show the bug but it now appears to be working as expected, I'l let you know if I run in to any more issues though.
